### PR TITLE
Fix ReferentialConstraint tag

### PR DESCRIPTION
**Pull request by kirill533**
Exclude v3SimpleIdentifierCache and v3SimpleIdentifierRegex tags from ReferentialConstraint

### CODE REVIEW

**Comment by c-harris** [comment]
Thanks for the pull request, two questions 
1) Why are the fields to be excluded? Was it something we overlooked?
2) could we have a change that does not include the change to composer.json?

**Comment by kirill533** [comment]
1. Those fields are not intended to be part of the metadata. I saw them excluded in other areas. Before the fix, my metadata looked like this:
image
This is how it should be:
image

2. Of course. Composer was not intended to be changed. Sorry. My first pull request to remove repository.

**Comment by c-harris** [comment]
Well I am happy to merge that one up :) thanks for helping out

**Comment by c-harris** [comment]
P.s. any other help you need with odata let us know:)

**Comment by kirill533** [comment]
Hi,

I actually try to use the package to integrate with Power BI, but that did
not work with the version  of Algo-Web. I found another fork and that had
some fixes to make it working.

Did you manage to connect with Power BI to odata interface created by your
version of POData?

Best regards,
Kirill

**Comment by c-harris** [comment]
Yes about 2 years ago through the podata-laravel project. Do you want to raise an issue on the podata package and I'll see if I can work through it with you?

**Comment by kirill533** [comment]
Hi,

That would be great if I would do that at the beginning when I tried to use
algo-web version only. Right now I am quite far in merging with another
fork and I do not even know exactly why the version from algo-web did not
work. It could even be that I made some mistake outside of the project and
that got fixed later.

But the main difference that I see is that the branch I try to use gives
formal like
{
"odata.metadata": '..."
"value" : {}
}

whereas algo-web for the same request provides something like
{
"d": {}
}

I also tried to setup podata-laravel, but used laravel version is not
compatible with Mysql 8.0 due to some bug. Upgrading laravel was also not
an easy task.

But if you do not mind, I would be glad to have a call with you to know
more about the project and the motivation behind it. I will also introduce
myself and will explain you how I may use the POData project.

Best regards,
Kirill

**Comment by kirill533** [comment]
Hi Harris,
just wanted to let you know: with some help from Alex Goodwin, I managed to make podata-laravel working with latest version of Power BI. That requires small fix that I already posted in another pull request. Thanks a lot for your support!
Best regards,
Kirill

**Comment by c-harris** [comment]
Glad to hear that, anything else you need just let me know.

**Pull request merged**
