### PR TITLE
Fix EDMX Version

### PR DESCRIPTION
**Pull request by kirill533**
https://github.com/Algo-Web/ODataMetadata/issues/139

### CODE REVIEW

**Comment by c-harris** [comment]
Thank you for this one, I have had some trouble with the version tag as the documentation on the topic is, well let's say "less then helpful" I will merge this up when I get home will fix the CI issues and probably cut a new bugfiz tag

**Comment by CyberiaResurrection** [comment]
Rolling up to get this fix landed pending @c-harris cleaning up CI

**Comment by c-harris** [comment]
@kirill533 if you found that you wanted to email me directly about any of the odata stuff you can pull my email from the composer json

**Comment by CyberiaResurrection** [comment]
Credit where credit is due again, @kirill533 , as 0.1.2 has landed:

https://github.com/Algo-Web/ODataMetadata/blob/master/CHANGELOG.md

**Pull request merged**
